# Generated by Django 3.1.3 on 2021-11-10 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Class', models.CharField(blank=True, choices=[('BR', 'Beverage'), ('ME', 'Medicine'), ('CO', 'Cosmetics'), ('DN', 'Daily Necessity')], max_length=2, null=True)),
                ('Second_Class', models.CharField(blank=True, max_length=50, null=True)),
                ('Product_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Price', models.IntegerField(blank=True, default=0, null=True)),
                ('Expiration_Date', models.DateField(blank=True, null=True)),
                ('Basic_Information', models.CharField(blank=True, max_length=200, null=True)),
                ('Notice', models.CharField(blank=True, max_length=200, null=True)),
                ('Additional_Information', models.CharField(blank=True, max_length=200, null=True)),
                ('User_Review', models.CharField(blank=True, max_length=200, null=True)),
                ('Realtime_Information', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
