# Generated by Django 3.1.3 on 2021-11-15 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('showpping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blind_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Permission_check', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product_info',
            name='Realtime_Information',
        ),
        migrations.RemoveField(
            model_name='product_info',
            name='User_Review',
        ),
        migrations.AlterField(
            model_name='product_info',
            name='First_Class',
            field=models.CharField(blank=True, choices=[('음료', '음료'), ('의약품', '의약품'), ('화장품', '화장품'), ('생필품', '생필품')], max_length=5, null=True),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Review', models.CharField(blank=True, max_length=200, null=True)),
                ('Realtime_Information', models.CharField(blank=True, max_length=200, null=True)),
                ('create_date', models.DateTimeField()),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showpping.product_info')),
            ],
        ),
    ]
