# Generated by Django 3.1.3 on 2021-11-16 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('showpping', '0003_auto_20211116_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='Realtime_Information',
        ),
        migrations.AlterField(
            model_name='review',
            name='User_Review',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Rinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Realtime_Information', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showpping.product_info')),
            ],
        ),
    ]
