# Generated by Django 3.1.3 on 2021-11-17 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showpping', '0005_auto_20211116_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rinfo',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
