# Generated by Django 3.1.3 on 2021-12-24 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showpping', '0008_auto_20211117_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_info',
            name='barcode_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
