# Generated by Django 3.1.3 on 2021-12-27 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showpping', '0009_product_info_barcode_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_info',
            name='Manufacturer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
